/**
 * AccountPage metin varsayılanları (ikas.config.json defaultValue ile aynı).
 * Editörde boş bırakılmayan (undefined olmayan) değer bunların üstüne yazılır; "" metni gizler.
 * Spec: docs/account-pages.md §3.
 */
export const ACCOUNT_TEXTS = {
  eyebrow: "✦",
  gateTitle: "Giriş yapman gerekiyor",
  gateText: "Siparişlerini, adreslerini ve favorilerini görmek için hesabına giriş yap.",
  gateButton: "Giriş Yap",
  loadingText: "Yükleniyor…",
  closeLabel: "Kapat",
  cancelText: "Vazgeç",
  retryText: "Tekrar dene",
  decreaseLabel: "Azalt",
  increaseLabel: "Artır",
  navLabel: "Hesap menüsü",
  navProfile: "Kişisel Bilgilerim",
  navOrders: "Siparişlerim",
  navAddresses: "Adreslerim",
  navFavorites: "Favorilerim",
  navLogout: "Çıkış Yap",
  greetingText: "Merhaba, {name}",
  profileIntro: "Siparişlerini, adreslerini ve favori tasarımlarını buradan yönetebilirsin.",
  statOrders: "Sipariş",
  statAddresses: "Kayıtlı Adres",
  statFavorites: "Favori",
  lastOrderTitle: "Son Siparişin",
  allOrdersText: "Tüm siparişlerim",
  noOrdersText: "Henüz bir siparişin yok.",
  infoTitle: "Kişisel Bilgiler",
  firstNameLabel: "Ad",
  lastNameLabel: "Soyad",
  emailLabel: "E-posta",
  emailLockText: "(değiştirilemez)",
  phoneLabel: "Telefon",
  phoneHint: "(isteğe bağlı)",
  phonePlaceholder: "+90 5__ ___ __ __",
  marketingText: "Yeni koleksiyonlar ve kampanyalardan e-posta ile haberdar olmak istiyorum.",
  saveText: "Kaydet",
  savingText: "Kaydediliyor…",
  saveSuccessText: "Bilgilerin güncellendi.",
  saveErrorText: "Bilgilerin kaydedilemedi. Lütfen tekrar dene.",
  passwordTitle: "Şifre",
  passwordText: "Şifreni değiştirmek için e-posta adresine bir sıfırlama bağlantısı gönderiyoruz.",
  passwordLinkText: "Şifremi sıfırla",
  privacyTitle: "Verilerin",
  exportText: "Verilerimin kopyasını gönder",
  exportingText: "Gönderiliyor…",
  exportSuccessText: "Kişisel verilerinin bir kopyası e-posta adresine gönderildi.",
  exportErrorText: "İstek gönderilemedi. Lütfen tekrar dene.",
  deleteLinkText: "Hesabımı sil",
  deleteTitle: "Hesabını silmek istediğine emin misin?",
  deleteWarningText: "Bu işlem geri alınamaz. Siparişlerin ve kişiselleştirme dosyaların, yasal saklama süresi boyunca KVKK kapsamında saklanmaya devam edebilir.",
  deletePasswordLabel: "Onaylamak için şifren",
  showPasswordLabel: "Şifreyi göster",
  hidePasswordLabel: "Şifreyi gizle",
  deleteConfirmText: "Hesabımı Sil",
  deletingText: "Siliniyor…",
  deleteSuccessText: "Hesap silme talebin alındı. Çıkış yapılıyor…",
  deletePendingText: "Zaten işlemde olan bir hesap silme talebin var.",
  deleteErrorText: "Hesabın silinemedi. Şifreni kontrol edip tekrar dene.",
  ordersIntro: "",
  ordersEmptyText: "Henüz bir siparişin yok. İlk sikkeni atölyede tasarla.",
  orderNoLabel: "Sipariş No",
  orderDateLabel: "Tarih",
  orderItemsText: "{count} ürün",
  orderTotalLabel: "Toplam",
  orderDetailText: "Detayı Gör",
  showMoreText: "Daha fazla göster",
  ordersErrorText: "Siparişlerin yüklenemedi.",
  statusPreparing: "Hazırlanıyor",
  statusShipped: "Kargoya Verildi",
  statusDelivered: "Teslim Edildi",
  statusCancelled: "İptal Edildi",
  statusCancelRequested: "İptal Talebi Alındı",
  statusRefundProcess: "İade Sürecinde",
  statusRefunded: "İade Edildi",
  statusRejected: "Talep Reddedildi",
  statusProblem: "Teslim Edilemedi",
  backToOrdersText: "Siparişlerime dön",
  orderTitle: "Sipariş #{no}",
  orderNotFoundText: "Bu sipariş bulunamadı.",
  itemsTitle: "Ürünler",
  frontLabel: "Ön",
  backLabel: "Arka",
  platingLabel: "24 Ayar Altın Kaplama",
  detailsLabel: "Tasarım Detayları",
  yesText: "Evet",
  photoOpenText: "Fotoğrafı aç",
  photoErrorText: "Dosya açılamadı",
  quantityLabel: "Adet",
  shippingAddressTitle: "Teslimat Adresi",
  billingAddressTitle: "Fatura Adresi",
  paymentTitle: "Ödeme",
  installmentText: "{count} Taksit",
  singlePaymentText: "Tek Çekim",
  summaryTitle: "Sipariş Özeti",
  subtotalLabel: "Ara Toplam",
  shippingLabel: "Kargo",
  freeShippingText: "Ücretsiz",
  totalLabel: "Toplam",
  taxIncludedText: "KDV dahil",
  cargoTitle: "Kargo Takibi",
  packageLabel: "Paket",
  cargoCompanyLabel: "Kargo Firması",
  trackingNumberLabel: "Takip No",
  copyText: "Kopyala",
  copiedText: "Kopyalandı",
  trackText: "Kargoyu Takip Et",
  notShippedText: "Kargo bilgisi, paketin kargoya verildiğinde burada görünecek.",
  refundButtonText: "İade Talebi Oluştur",
  refundTitle: "İade Talebi",
  refundIntro: "İade etmek istediğin ürünleri ve adetlerini seç.",
  refundNoticeText: "Kişiye özel üretilen sikkeler, üretim hatası dışında iade edilemez. Ayrıntılar için {link}.",
  refundReasonText: "İade nedenini {link} üzerinden bize iletebilirsin.",
  refundQuantityLabel: "İade adedi",
  refundSubmitText: "Talebi Gönder",
  refundSubmittingText: "Gönderiliyor…",
  refundSuccessText: "İade talebin alındı. En kısa sürede seninle iletişime geçeceğiz.",
  refundErrorText: "İade talebi gönderilemedi. Lütfen tekrar dene.",
  refundedTitle: "İade Taleplerin",
  addressesEmptyText: "Henüz kayıtlı bir adresin yok.",
  addAddressText: "Yeni Adres Ekle",
  defaultBadgeText: "Varsayılan",
  editText: "Düzenle",
  deleteText: "Sil",
  deleteAddressTitle: "Adresi sil",
  deleteAddressText: "“{title}” adresini silmek istediğine emin misin?",
  deleteAddressConfirm: "Adresi Sil",
  deleteAddressErrorText: "Adres silinemedi. Lütfen tekrar dene.",
  addTitle: "Yeni Adres",
  editTitle: "Adresi Düzenle",
  addressSaveText: "Adresi Kaydet",
  addressSavingText: "Kaydediliyor…",
  addressErrorText: "Adres kaydedilemedi. Lütfen tekrar dene.",
  addrTitleLabel: "Adres Başlığı",
  addrTitlePlaceholder: "Ev, İş…",
  addrFirstNameLabel: "Ad",
  addrLastNameLabel: "Soyad",
  addrIdentityLabel: "T.C. Kimlik No",
  addrLine1Label: "Adres",
  addrLine1Placeholder: "Cadde, sokak, bina ve daire no",
  addrLine2Label: "Adres (devam)",
  addrPostalCodeLabel: "Posta Kodu",
  addrCountryLabel: "Ülke",
  addrStateLabel: "Eyalet",
  addrCityLabel: "İl",
  addrDistrictLabel: "İlçe",
  addrRegionLabel: "Mahalle",
  addrPhoneLabel: "Telefon",
  selectPlaceholder: "Seçiniz",
  optionalHint: "(isteğe bağlı)",
  favoritesEmptyText: "Favori listen boş. Beğendiğin tasarımları kalp simgesiyle buraya ekleyebilirsin.",
  designText: "Tasarla",
  removeFavoriteLabel: "Favorilerden çıkar",
  favoritesErrorText: "Favorilerin yüklenemedi.",
  requiredError: "Bu alan zorunlu.",
  phoneError: "Geçerli bir telefon numarası gir.",
  invalidError: "Bu alanı kontrol et.",
};

export type AccountTexts = typeof ACCOUNT_TEXTS;

/** Section prop değerlerini varsayılanlarla birleştirir (yalnız undefined olanlar varsayılana düşer). */
export function accountTexts(props: Partial<Record<keyof AccountTexts, string | undefined>>): AccountTexts {
  const out = { ...ACCOUNT_TEXTS };
  for (const key of Object.keys(ACCOUNT_TEXTS) as Array<keyof AccountTexts>) {
    const v = props[key];
    if (typeof v === "string") out[key] = v;
  }
  return out;
}

/** "{name}" gibi yer tutucuları doldurur. */
export function fill(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}
