// This file is auto-generated — do not edit manually.
import type { IkasProduct, IkasImage } from "@ikas/bp-storefront";

export interface Props {
  /** Materyal varyantlı (925 / 14K / 22K) ana ürün; opsiyon seti bu ürüne bağlı olmalı */
  product?: IkasProduct | null;
  /** Materyal varyantlı hediye sertifikası ürünü (hediye modu) */
  giftProduct?: IkasProduct | null;
  romaMGold?: IkasImage | null;
  romaMGoldNobust?: IkasImage | null;
  romaMSilver?: IkasImage | null;
  romaMSilverNobust?: IkasImage | null;
  romaFGold?: IkasImage | null;
  romaFGoldNobust?: IkasImage | null;
  romaFSilver?: IkasImage | null;
  romaFSilverNobust?: IkasImage | null;
  osmanliMGold?: IkasImage | null;
  osmanliMGoldNosarik?: IkasImage | null;
  osmanliMSilver?: IkasImage | null;
  osmanliMSilverNosarik?: IkasImage | null;
  osmanliFGold?: IkasImage | null;
  osmanliFGoldNosarik?: IkasImage | null;
  osmanliFSilver?: IkasImage | null;
  osmanliFSilverNosarik?: IkasImage | null;
  misirMGold?: IkasImage | null;
  misirMSilver?: IkasImage | null;
  misirFGold?: IkasImage | null;
  misirFSilver?: IkasImage | null;
  photoGuideImage?: IkasImage | null;
  glyphGuideImage?: IkasImage | null;
  eyebrow?: string;
  title?: string;
  titleAccent?: string;
  description?: string;
  faceFrontLabel?: string;
  faceBackLabel?: string;
  flipLabel?: string;
  clearLabel?: string;
  priceLabel?: string;
  priceSub?: string;
  priceUnavailableText?: string;
  step1Num?: string;
  step1Title?: string;
  step1TitleAccent?: string;
  step1Hint?: string;
  materialSilverName?: string;
  material14kName?: string;
  material22kName?: string;
  specSilver?: string;
  spec14k?: string;
  spec22k?: string;
  coinDiameter?: string;
  specNote?: string;
  platingTitle?: string;
  platingDescSilver?: string;
  platingDesc14k?: string;
  platingFreeText?: string;
  materialMissingText?: string;
  step2Num?: string;
  step2Title?: string;
  step2TitleAccent?: string;
  step2Hint?: string;
  step3Num?: string;
  step3Title?: string;
  step3TitleAccent?: string;
  step3Hint?: string;
  backToggleText?: string;
  backToggleDesc?: string;
  faceDividerText?: string;
  themeLabel?: string;
  seriesRoma?: string;
  seriesOsmanli?: string;
  seriesMisir?: string;
  genderLabel?: string;
  genderMale?: string;
  genderFemale?: string;
  bustTitle?: string;
  bustDesc?: string;
  sarikTitle?: string;
  sarikDesc?: string;
  glyphNoticeTitle?: string;
  glyphNoticeText?: string;
  glyphGuideLabel?: string;
  glyphGuideSub?: string;
  nameLabel?: string;
  dateLabel?: string;
  dateSub?: string;
  suggestionsHint?: string;
  suggestionsMale?: string;
  suggestionsFemale?: string;
  suggestionSlot?: string;
  suggestionNoteMisir?: string;
  photoLabel?: string;
  photoSub?: string;
  photoSlotLabel?: string;
  uploadSub?: string;
  samePhotoText?: string;
  consentText?: string;
  consentInfoTitle?: string;
  consentInfoBody?: string;
  cancelInfoTitle?: string;
  cancelInfoBody?: string;
  consentMissingToast?: string;
  photoTooLargeToast?: string;
  photoTypeToast?: string;
  noteLabel?: string;
  noteOptional?: string;
  notePlaceholder?: string;
  step4Num?: string;
  step4Title?: string;
  step4TitleAccent?: string;
  step4Hint?: string;
  sumMaterial?: string;
  sumFront?: string;
  sumBack?: string;
  sumTotal?: string;
  addToCartText?: string;
  addingText?: string;
  productMissingText?: string;
  optionErrorText?: string;
  cartErrorText?: string;
  addedToast?: string;
  trust1?: string;
  trust2?: string;
  trust3?: string;
  trust4?: string;
  showGiftMode?: boolean;
  giftSelfText?: string;
  giftGiftText?: string;
  giftRedeemText?: string;
  giftIntro?: string;
  giftChooseLabel?: string;
  giftAddText?: string;
  giftAddedToast?: string;
  giftMissingText?: string;
  redeemIntro?: string;
  redeemPlaceholder?: string;
  redeemButton?: string;
  redeemOkText?: string;
  redeemErrText?: string;
  redeemAppliedLabel?: string;
  redeemFailedToast?: string;
  sealTitle?: string;
  sealText?: string;
  sealCancel?: string;
  sealConfirm?: string;
  pgTitle?: string;
  pgIntro?: string;
  pgCaption?: string;
  pgBody?: string;
  pgCancel?: string;
  pgConfirm?: string;
  /** Opsiyon adları bu önekle başlar: 'Yüz 1 · Seri' */
  optFace1?: string;
  optFace2?: string;
  optSeries?: string;
  optGender?: string;
  optBust?: string;
  optSarik?: string;
  optName?: string;
  optDate?: string;
  optRoman?: string;
  optPhotos?: string;
  optBackFace?: string;
  optPlating?: string;
  optConsent?: string;
  optNote?: string;
  anchorId?: string;
  backgroundColor?: string;
  photoUploadErrorToast?: string;
  styleTestLabel?: string;
  styleTestImage1?: IkasImage | null;
  styleTestAlt1?: string;
  styleTestImage2?: IkasImage | null;
  styleTestAlt2?: string;
  styleTestImage3?: IkasImage | null;
  styleTestAlt3?: string;
  descriptionMobile?: string;
  directionLabel?: string;
  directionSub?: string;
  directionLeft?: string;
  directionRight?: string;
  directionInfoAria?: string;
  chainLabel?: string;
  chainSub?: string;
  chain50Text?: string;
  chain55Text?: string;
  chain60Text?: string;
  dirModalTitle?: string;
  dirModalLead?: string;
  dirModalKicker?: string;
  dirModalSub?: string;
  dirClause1Title?: string;
  dirClause1Text?: string;
  dirClause2Title?: string;
  dirClause2Text?: string;
  dirClause3Title?: string;
  dirClause3Text?: string;
  dirClause4Title?: string;
  dirClause4Text?: string;
  dirModalCloseLabel?: string;
  optDirection?: string;
  optChain?: string;
  titleAsH1?: boolean;
  gnPaperRoma?: IkasImage | null;
  gnPaperOsmanli?: IkasImage | null;
  gnPaperMisir?: IkasImage | null;
  gnGlyphMask?: IkasImage | null;
  showGiftNote?: boolean;
  gnEyebrow?: string;
  gnTitle?: string;
  gnFacesSingle?: string;
  gnFacesDouble?: string;
  gnRuleOne?: string;
  gnRuleTwo?: string;
  gnAnd?: string;
  gnRomaSub?: string;
  gnOsmanliSub?: string;
  gnMisirSub?: string;
  gnLockedSub?: string;
  gnUvLabel?: string;
  gnPlaceholder?: string;
  gnGlyphPlaceholder?: string;
  gnSuggLabel?: string;
  gnRomaSugg1?: string;
  gnRomaSugg1Sub?: string;
  gnRomaSugg2?: string;
  gnRomaSugg2Sub?: string;
  gnRomaSugg3?: string;
  gnRomaSugg3Sub?: string;
  gnOsmanliSugg1?: string;
  gnOsmanliSugg1Sub?: string;
  gnOsmanliSugg2?: string;
  gnOsmanliSugg2Sub?: string;
  gnOsmanliSugg3?: string;
  gnOsmanliSugg3Sub?: string;
  gnMisirSugg1?: string;
  gnMisirSugg1Sub?: string;
  gnMisirSugg2?: string;
  gnMisirSugg2Sub?: string;
  gnMisirSugg3?: string;
  gnMisirSugg3Sub?: string;
  gnInputLabel?: string;
  gnInputPlaceholder?: string;
  gnSaveText?: string;
  gnSavedText?: string;
  gnSavedUvText?: string;
  gnSavedToast?: string;
  optGiftNote?: string;
  optParchment?: string;
  gnCardText?: string;
  gnOpenText?: string;
  gnEditText?: string;
  gnRemoveText?: string;
  gnMissingToast?: string;
}
