// This file is auto-generated — do not edit manually.
import type { IkasProduct, IkasImage } from "@ikas/bp-storefront";

export interface Props {
  /** Materyal varyantlı (925 / 14K / 22K) ana ürün; opsiyon seti bu ürüne bağlı olmalı */
  product?: IkasProduct | null;
  /** Materyal varyantlı hediye sertifikası ürünü (hediye modu) */
  giftProduct?: IkasProduct | null;
  romaMGold?: IkasImage | null;
  romaMGoldNobust?: IkasImage | null;
  romaMSilver?: IkasImage | null;
  romaMSilverNobust?: IkasImage | null;
  romaFGold?: IkasImage | null;
  romaFGoldNobust?: IkasImage | null;
  romaFSilver?: IkasImage | null;
  romaFSilverNobust?: IkasImage | null;
  osmanliMGold?: IkasImage | null;
  osmanliMGoldNosarik?: IkasImage | null;
  osmanliMSilver?: IkasImage | null;
  osmanliMSilverNosarik?: IkasImage | null;
  osmanliFGold?: IkasImage | null;
  osmanliFGoldNosarik?: IkasImage | null;
  osmanliFSilver?: IkasImage | null;
  osmanliFSilverNosarik?: IkasImage | null;
  misirMGold?: IkasImage | null;
  misirMSilver?: IkasImage | null;
  misirFGold?: IkasImage | null;
  misirFSilver?: IkasImage | null;
  photoGuideImage?: IkasImage | null;
  glyphGuideImage?: IkasImage | null;
  eyebrow?: string;
  title?: string;
  titleAccent?: string;
  description?: string;
  faceFrontLabel?: string;
  faceBackLabel?: string;
  flipLabel?: string;
  clearLabel?: string;
  priceLabel?: string;
  priceSub?: string;
  priceUnavailableText?: string;
  step1Num?: string;
  step1Title?: string;
  step1TitleAccent?: string;
  step1Hint?: string;
  materialSilverName?: string;
  material14kName?: string;
  material22kName?: string;
  specSilver?: string;
  spec14k?: string;
  spec22k?: string;
  coinDiameter?: string;
  specNote?: string;
  platingTitle?: string;
  platingDescSilver?: string;
  platingDesc14k?: string;
  platingFreeText?: string;
  materialMissingText?: string;
  step2Num?: string;
  step2Title?: string;
  step2TitleAccent?: string;
  step2Hint?: string;
  step3Num?: string;
  step3Title?: string;
  step3TitleAccent?: string;
  step3Hint?: string;
  backToggleText?: string;
  backToggleDesc?: string;
  faceDividerText?: string;
  themeLabel?: string;
  seriesRoma?: string;
  seriesOsmanli?: string;
  seriesMisir?: string;
  genderLabel?: string;
  genderMale?: string;
  genderFemale?: string;
  bustTitle?: string;
  bustDesc?: string;
  sarikTitle?: string;
  sarikDesc?: string;
  glyphNoticeTitle?: string;
  glyphNoticeText?: string;
  glyphGuideLabel?: string;
  glyphGuideSub?: string;
  nameLabel?: string;
  dateLabel?: string;
  dateSub?: string;
  suggestionsHint?: string;
  suggestionsMale?: string;
  suggestionsFemale?: string;
  suggestionSlot?: string;
  suggestionNoteMisir?: string;
  photoLabel?: string;
  photoSub?: string;
  photoSlotLabel?: string;
  uploadSub?: string;
  samePhotoText?: string;
  consentText?: string;
  consentInfoTitle?: string;
  consentInfoBody?: string;
  cancelInfoTitle?: string;
  cancelInfoBody?: string;
  consentMissingToast?: string;
  photoTooLargeToast?: string;
  photoTypeToast?: string;
  noteLabel?: string;
  noteOptional?: string;
  notePlaceholder?: string;
  step4Num?: string;
  step4Title?: string;
  step4TitleAccent?: string;
  step4Hint?: string;
  sumMaterial?: string;
  sumFront?: string;
  sumBack?: string;
  sumTotal?: string;
  addToCartText?: string;
  addingText?: string;
  productMissingText?: string;
  optionErrorText?: string;
  cartErrorText?: string;
  addedToast?: string;
  trust1?: string;
  trust2?: string;
  trust3?: string;
  trust4?: string;
  showGiftMode?: boolean;
  giftSelfText?: string;
  giftGiftText?: string;
  giftRedeemText?: string;
  giftIntro?: string;
  giftChooseLabel?: string;
  giftAddText?: string;
  giftAddedToast?: string;
  giftMissingText?: string;
  redeemIntro?: string;
  redeemPlaceholder?: string;
  redeemButton?: string;
  redeemOkText?: string;
  redeemErrText?: string;
  redeemAppliedLabel?: string;
  redeemFailedToast?: string;
  sealTitle?: string;
  sealText?: string;
  sealCancel?: string;
  sealConfirm?: string;
  pgTitle?: string;
  pgIntro?: string;
  pgCaption?: string;
  pgBody?: string;
  pgCancel?: string;
  pgConfirm?: string;
  /** Opsiyon adları bu önekle başlar: 'Yüz 1 · Seri' */
  optFace1?: string;
  optFace2?: string;
  optSeries?: string;
  optGender?: string;
  optBust?: string;
  optSarik?: string;
  optName?: string;
  optDate?: string;
  optRoman?: string;
  optPhotos?: string;
  optBackFace?: string;
  optPlating?: string;
  optConsent?: string;
  optNote?: string;
  anchorId?: string;
  backgroundColor?: string;
}
