// This file is auto-generated — do not edit manually.
import type { IkasNavigationLink } from "@ikas/bp-storefront";

export interface Props {
  eyebrow?: string;
  gateTitle?: string;
  gateText?: string;
  gateButton?: string;
  loadingText?: string;
  closeLabel?: string;
  cancelText?: string;
  retryText?: string;
  navLabel?: string;
  navProfile?: string;
  navOrders?: string;
  navAddresses?: string;
  navFavorites?: string;
  navLogout?: string;
  /** {name} yerine müşterinin adı gelir. */
  greetingText?: string;
  profileIntro?: string;
  statOrders?: string;
  statAddresses?: string;
  statFavorites?: string;
  lastOrderTitle?: string;
  allOrdersText?: string;
  noOrdersText?: string;
  infoTitle?: string;
  firstNameLabel?: string;
  lastNameLabel?: string;
  emailLabel?: string;
  emailLockText?: string;
  phoneLabel?: string;
  phoneHint?: string;
  phonePlaceholder?: string;
  marketingText?: string;
  saveText?: string;
  savingText?: string;
  saveSuccessText?: string;
  saveErrorText?: string;
  passwordTitle?: string;
  passwordText?: string;
  passwordLinkText?: string;
  privacyTitle?: string;
  exportText?: string;
  exportingText?: string;
  exportSuccessText?: string;
  exportErrorText?: string;
  deleteLinkText?: string;
  deleteTitle?: string;
  deleteWarningText?: string;
  deletePasswordLabel?: string;
  showPasswordLabel?: string;
  hidePasswordLabel?: string;
  deleteConfirmText?: string;
  deletingText?: string;
  deleteSuccessText?: string;
  deletePendingText?: string;
  deleteErrorText?: string;
  ordersIntro?: string;
  ordersEmptyText?: string;
  ordersEmptyLink?: IkasNavigationLink | null;
  orderNoLabel?: string;
  orderDateLabel?: string;
  /** {count} yerine ürün adedi gelir. */
  orderItemsText?: string;
  orderTotalLabel?: string;
  orderDetailText?: string;
  showMoreText?: string;
  ordersErrorText?: string;
  statusPreparing?: string;
  statusShipped?: string;
  statusDelivered?: string;
  statusCancelled?: string;
  statusCancelRequested?: string;
  statusRefundProcess?: string;
  statusRefunded?: string;
  statusRejected?: string;
  statusProblem?: string;
  backToOrdersText?: string;
  /** {no} yerine sipariş numarası gelir. */
  orderTitle?: string;
  orderNotFoundText?: string;
  itemsTitle?: string;
  frontLabel?: string;
  backLabel?: string;
  /** Kaplama opsiyonu işaretliyse satır başlığına eklenir */
  platingLabel?: string;
  detailsLabel?: string;
  yesText?: string;
  photoOpenText?: string;
  photoErrorText?: string;
  quantityLabel?: string;
  shippingAddressTitle?: string;
  billingAddressTitle?: string;
  paymentTitle?: string;
  /** {count} yerine taksit sayısı gelir. */
  installmentText?: string;
  singlePaymentText?: string;
  summaryTitle?: string;
  subtotalLabel?: string;
  shippingLabel?: string;
  freeShippingText?: string;
  totalLabel?: string;
  taxIncludedText?: string;
  cargoTitle?: string;
  packageLabel?: string;
  cargoCompanyLabel?: string;
  trackingNumberLabel?: string;
  copyText?: string;
  copiedText?: string;
  trackText?: string;
  notShippedText?: string;
  refundButtonText?: string;
  refundTitle?: string;
  refundIntro?: string;
  /** {link} yerine İade Şartları Linki gelir. */
  refundNoticeText?: string;
  refundPolicyLink?: IkasNavigationLink | null;
  /** {link} yerine İletişim Linki gelir. */
  refundReasonText?: string;
  refundContactLink?: IkasNavigationLink | null;
  refundQuantityLabel?: string;
  refundSubmitText?: string;
  refundSubmittingText?: string;
  refundSuccessText?: string;
  refundErrorText?: string;
  refundedTitle?: string;
  addressesEmptyText?: string;
  addAddressText?: string;
  defaultBadgeText?: string;
  editText?: string;
  deleteText?: string;
  deleteAddressTitle?: string;
  /** {title} yerine adres başlığı gelir. */
  deleteAddressText?: string;
  deleteAddressConfirm?: string;
  deleteAddressErrorText?: string;
  addTitle?: string;
  editTitle?: string;
  addressSaveText?: string;
  addressSavingText?: string;
  addressErrorText?: string;
  addrTitleLabel?: string;
  addrTitlePlaceholder?: string;
  addrFirstNameLabel?: string;
  addrLastNameLabel?: string;
  addrIdentityLabel?: string;
  addrLine1Label?: string;
  addrLine1Placeholder?: string;
  addrLine2Label?: string;
  addrPostalCodeLabel?: string;
  addrCountryLabel?: string;
  addrStateLabel?: string;
  addrCityLabel?: string;
  addrDistrictLabel?: string;
  addrRegionLabel?: string;
  addrPhoneLabel?: string;
  selectPlaceholder?: string;
  optionalHint?: string;
  favoritesEmptyText?: string;
  favoritesEmptyLink?: IkasNavigationLink | null;
  designText?: string;
  removeFavoriteLabel?: string;
  favoritesErrorText?: string;
  requiredError?: string;
  phoneError?: string;
  invalidError?: string;
  /** Gündüz modunda section zemini */
  backgroundColor?: string;
  decreaseLabel?: string;
  increaseLabel?: string;
  /** Kapalıyken menüde ve Hesabım özetinde Favoriler görünmez */
  showFavorites?: boolean;
}
